export enum Roles {
  ADMIN = "ADMIN",
  INVENTORY = "INVENTORY",
  READONLY = "READONLY",
  ORDER = "ORDER",
  CUSTOMER = "CUSTOMER",
  STOCKREPRICER = "STOCK REPRICER",
  DASHBOARD = "DASHBOARD",
  REPORTS = "REPORTS",
}
