// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.
export const environment = {
  production: false,
  defaultPaginationValue: 25,
  defaultTotalValue: 100,
  numberOfTabs: 5,
  maxNumberOfTabsAllowed: 8,
  ui_base_url: 'http://localhost:4200/sellershub/',
  // Report
  repo_getReportByProduct: '/findsaleproductreport',
  activateUser: '/activateUser',
  repo_lowStockReports: '/findlowstockproductreport',
  repo_getStockValueReport: '/findstockvaluereport',
  repo_getReportorderhistory: '/orderhistory',
  repo_getStockValueOrder: '/stockvaluereport',
  repo_export: '/new/exportOrders',
  // Inventory
  inv_getProducts: '/rest/dynamicSearch',
  inv_getChannelproducts: '/rest/findAllChannelProducts',
  inv_getStockview: '/rest/stockitemsview',
  removeProduct: '/rest/removekartzhubproducts',
  create_bundle_product: '/rest/createbundleproduct',
  update_bundle_product: '/rest/updatebundleproduct',
  link_product: '/rest/linkproducts',
  update_tracking:'/rest/updateTracking',
  unlink_product: '/rest/unlinkproducts',
  confirem_link_products: '/rest/confirmlinkproducts',
  confirem_unlink_products: '/rest/confirmlinkproducts',
  excluseSKUFrominven: '/rest/skuWiseInventorySync',
  startAddToChannel: '/rest/startaddtochannel',
  addToChannel: '/rest/addtochannel',
  getCurrencyCodes: '/rest/gettocurrencyvalue',
  update_bulk_revise_price: '/rest/updateprice',
  view_order_details: '/rest/viewOrderDetails',
  view_kartzhub_products:'/channelintegration/viewKartzhubProducts',
  view_channel_products:'/channelintegration/viewChannelProducts',
  createMapLinkSku:'/channelintegration/createMapLinkSku',
  updateSplitRules:'/channelintegration/updateSplitRules',
  // Warehouse
  update_transfer: "/updatestocktransfer",
  ware_getWarehouse: '/warehouse/warehouse',
  ware_getStocksummary: '/warehouse/stockitemsview',
  ware_getTransfer: '/warehouse/stocktransferitem',
  ware_removewarehouse: '/warehouse/removewarehouse',
  ware_removewarehouse_location: '/warehouse/removewarehouselocation',
  ware_editwarehouse: '/warehouse/editwarehouse',
  ware_updatewarehouse: '/warehouse/updatewarehouse',
  ware_findwarehouselocations: '/warehouse/findwarehouselocations',
  ware_editwarehouselocation: '/warehouse/editwarehouselocation',
  ware_updatewarehouselocation: '/warehouse/updatewarehouselocation',
  ware_getStock: '/rest/stockitem',
  ware_findcurrentlocationsforsku: '/findcurrentlocationsforsku',
  ware_findcurrentlocationsforskutransfer: '/findcurrentlocationsforskutransfer',
  ware_updatestockforlocations: '/updatestockforlocations',
  ware_updatestocktransfer: '/updatestocktransfer',
  ware_productNew: '/productnew',
  ware_assignlocationforProduct: '/assignlocationforproducts',
  ware_showProduct: '/showproductswarehouselocation',

  //Orders
  order_getOrderSummary: '/new/orderspagesummary',
  order_getSalesOrders: '/new/dynamicSearch',
  dynamicSearchOrders: '/new/dynamicSearchOrders',
  order_getShippedOrdersSearch: '/new/shippedorders',
  order_getMcfOrders: '/new/viewfbaorders',
  order_findMcfOrders: '/new/findfbaorders',
  order_getCancelledOrders: '/new/getcancelledorderslist',
  order_getReturnedOrderspara: '/new/returnedordersdata',
  order_notes_list: '/new/displayComments',
  order_notes_create: '/new/loadordercomments',
  cancelorder: '/new/cancelorder',
  //sales Order Sub
  downloadordersfromchannels: '/new/downloadordersfromchannels',
  applydownloadordersfromchannelid: '/new/applydownloadordersfromchannelid',
  orderDetailsBasedonOrderID: '/new/searchOrderId',
  searchOrderTrackingId: '/new/searchOrderTrackingId',
  confirmorderpayment: '/new/confirmorderpayment',
  bulkemail: '/new/bulkemail',
  orderProcess: '/new/orderProcess',
  findOrdercancel: '/new/findordersforcancel',
  findOrdercancelv2: '/orderutility/orderitems',
  createPickList: '/new/exportpicklist',
  createPackList: '/new/exportpacklist',
  emailGetInfo: '/new/bulkemail',
  mergeOrder: '/orderutility/merge',
  unmergeOrder: 'orderutility/undomerge',
  splitOrder_Orderitems: '/orderutility/orderitems',
  splitOrder: '/orderutility/split',
  undoSplitOrder: '/orderutility/undosplit',
  print_lablesMenus: '/shippingcourier/all',
  labelDetails: '/new/loadcuriershippingservices',
  confirm_shipment: '/new/confirmshipment',
  findOrdersForShipping: '/new/findordersforshipment',
  finddraftorders: '/new/finddraftorders',
  removeOrdersFromDraft: '/new/removeorder',
  productnew: '/productnew',
  createOrder: '/new/createorder',
  updateSaleItem: '/new/updatesaleitem',
  removeProductSaleItem: '/new/removeproductfromorder',
  saveOrder: '/new/saveorder',
  addProductToOrder: '/new/addproducttoorder',
  editOrderDetails: '/new/editeachorderitem',
  expired_products: '/findexpireProductdate',
  // sendEmailConfirm:'/new/sendemailconfirm',
  sendEmailConfirm: '/new/sendbulkemailconfirm',
  printInvoice: '/new/bulkprintinvoices',
  exportOrdertoCsv: '/orderutility/orders',
  //exports
  exportSaleProductReport: '/new/exportSaleProductReport',
  exportStockValueReport: '/new/exportStockValueReport',
  exportLowStockReport: '/new/exportLowStockReport',
  exportOrderReport: '/new/exportOrderReport',
  exportOrderHistoryReport: '/new/exportOrderHistoryReport',
  exportChannelProductsReport: '/new/exportChannelProductsReport',
  exportPickingListReport: '/new/exportPickingListReport',
  exportPackingListReport: '/new/exportPackingListReport',
  //Dashboard API's
  das_dashboardnew: '/dashboardnew',
  dash_ordersummary: '/ordersummary',
  dash_loadsalesbychannel: '/loadsalesbychannel',
  dash_inventorysummary: '/inventorysummary',
  dash_loadsalesbycountry: '/loadsalesbycountry',
  dash_loadorderhistory: '/loadorderhistory',
  //Messages In headers
  msg_listmsg: '/messages',
  msg_replymsg: '/replytomessage',
  msg_replySavemsg: '/savereplymessage',
  msg_showmsg: '/showmessagedetails',
  //Customers
  cust_customerlist: '/Customers/list',
  savecustomer: '/Customers/savecustomer',
  find_searchname:'/Customers/findSearchName',
  BASE_URL: 'https://login.sellershub.io',
  user_profile: '/user',
  //Listing
  list_waitingtolist: '/listing/findproductwaitingtolistData',
  list_listingerrors: '/listing/findproductlistingerrorsdata',
  list_listedproduct: '/listing/listedproducts',
  list_closedproduct: '/listing/findproductcloseditemsdata',
  list_schedulelisting: '/listing/findscheduledlistings',
  list_createproductstofba: '/listing/createfbashipment',
  list_sendproducttofba: '/listing/listshipment',
  // list_productstofba: '/listing/findfulfilmentproducts',
  list_productstofba: '/listing/findfulfilmentproductssearch',
  list_selectlistingtemplate: '/listing/selectlistingtemplateupdatechannel',
  list_updatetemplate: '/listing/updatelistingtemplateforchannelproducts',
  list_updateChanneltemplate: '/listing/updateChannel',
  list_removeerrorlist: '/listing/removeerrorlist',
  list_removewaitinglist: '/listing/removewaitinglist',
  list_shipmentitems: '/listing/listshipmentitems',
  list_newinboundshipment: '/listing/newinboundshipment',
  // Suppliers
  supl_supplier: '/new/suppliers',

  supl_feed: '/feed',
  supl_remove: '/new/removesupplier',
  supl_remove_product: '/new/removesupplierproduct',
  supl_add: '/new/updatesupplier',
  supl_edit: '/new/editsupplier',
  save_product_suppliers: '/new/saveproductSupplierslist',
  get_prod_supplier: '/new/findcurrentsuppliersforsku',

  //Integrations
  inte_shippingCourier: '/shippingcourier/all',
  inte_channelRegistration: '/channeluser',
  add_shippingmethod:'/new/updateordershippingmethod',
  inte_ebaygenerateTokenNew: '/channelintegration/ebaytoken',
  inte_ebaygenerateToken: '/channelintegration/ebay/ebaytoken',
  inte_ebaytestCon: '/channelintegration/ebay/testconnection',
  inte_ebaydownloadAllProduct: '/channelintegration/ebay/downloadallproducts',
  inte_ebaydownloadrecentProduct: '/channelintegration/ebay/downloadrecentproduct',
  inte_ebay: '/channelintegration/ebay',
  findebayitemspecificsfortemplate: '/findebayitemspecificsfortemplate',
  findebayitemspecifics: '/findebayitemspecifics',
  amazon_existing_data: '/channelintegration/amazon',
  amazon_test_connection: '/channelintegration/amazon/testconnection',
  amazon_download_recent_prod: '/channelintegration/amazon/downloadrecentproducts',
  amazon_downloadAllProducts: '/channelintegration/amazon/downloadallproducts',
  get_all_stores:'/clickandcollect/getAllStores',
  get_storesById:'/clickandcollect/getStoreById',
  create_stores:'/clickandcollect/createStore',
  update_stores:'/clickandcollect/updateStore',
  delete_stores:'/clickandcollect/archiveStore',
  update_store_status:'/clickandcollect/updateStoreStatus',
  update_shipstatus:'/clickandcollect/updateClickAndCollectShipmentStatus',
  find_all_orders:'/clickandcollect/findAllISPUOrders',
  inventory_update:'/clickandcollect/cncInventoryUpdate',
  shopify_existingData: '/channelintegration/shopify',
  walmart_existingData: '/channelintegration/walmart',
  shopwired_existingData: '/channelintegration/shopwired',
  bigcommerce_existingData: '/channelintegration/bigcommerce',
  kashflow_existingData: '/accounting/savekashflow',
  shopify_testConnection: '/channelintegration/shopify/testconnection',
  walmart_testConnection: '/channelintegration/walmart/testconnection',
  shopwired_testConnection: '/channelintegration/shopwired/testconnection',
  bigcommerce_testConnection: '/channelintegration/bigcommerce/testconnection',
  shopify_downloadRecent_prod: '/channelintegration/amazon/downloadrecentproducts',
  walmart_downloadRecent_prod: '/channelintegration/amazon/downloadrecentproducts',
  shopify_download_all_prod: '/channelintegration/shopify/downloadallproducts',
  walmart_download_all_prod: '/channelintegration/walmart/downloadallproducts',
  shopwired_download_all_prod: '/channelintegration/shopwired/downloadallproducts',
  bigcommerce_download_all_prod: '/channelintegration/bigcommerce/downloadallproducts',
  prestashop_existingData: '/channelintegration/prestashop',
  prestashop_testConnection: '/channelintegration/prestashop/testconnection',
  prestashop_downloadRecent_prod: '/channelintegration/amazon/downloadrecentproducts',
  prestashop_download_all_prod: '/channelintegration/prestashop/downloadallproducts',
  woocommerce_existingData: '/channelintegration/woocommerce',
  woocommerce_testConnection: '/channelintegration/woocommerce/testconnection',
  woocommerce_downloadRecent_prod: '/channelintegration/amazon/downloadrecentproducts',
  woocommerce_download_all_prod: '/channelintegration/woocommerce/downloadallproducts',
  magento2_existingData: '/channelintegration/magento2',
  magento2_testConnection: '/channelintegration/magento2/testconnection',
  magento2_downloadRecent_prod: '/channelintegration/amazon/downloadrecentproducts',
  magento2_download_all_prod: '/channelintegration/magento2/downloadallproducts',
  onbuy_existingData: '/channelintegration/onbuy',
  onbuy_testConnection: '/channelintegration/onbuy/testconnection',
  onbuy_downloadRecent_prod: '/channelintegration/onbuy/downloadrecentproducts',
  onbuy_download_all_prod: '/channelintegration/onbuy/downloadallproducts',
  onbuy_tocken: '/channelintegration/generateonbuytoken',
  etsy_existingData: '/channelintegration/etsy',
  etsy_testConnection: '/channelintegration/etsy/testconnection',
  etsy_downloadRecent_prod: '/channelintegration/etsy/downloadrecentproducts',
  etsy_download_all_prod: '/channelintegration/etsy/downloadallproducts',
  etsy_tocken: '/generateetsytoken',
  amazon_subcategories: '/findamazonsubcategories',
  amazon_browsernodes: '/searchamazonbrowsernodes',
  sears_existingData: '/channelintegration/sears',
  sears_testConnection: '/channelintegration/sears/testconnection',
  sears_downloadRecent_prod: '/channelintegration/sears/downloadrecentproducts',
  sears_download_all_prod: '/channelintegration/sears/downloadallproducts',
  cdiscount_existingData: '/channelintegration/cdiscount',
  cdiscount_testConnection: '/channelintegration/cdiscount/testconnection',
  cdiscount_downloadRecent_prod: '/channelintegration/cdiscount/downloadrecentproducts',
  cdiscount_download_all_prod: '/channelintegration/cdiscount/downloadallproducts',
  priceminister_existingData: '/channelintegration/priceminister',
  priceminister_testConnection: '/channelintegration/priceminister/testconnection',
  priceminister_downloadRecent_prod: '/channelintegration/priceminister/downloadrecentproducts',
  priceminister_download_all_prod: '/channelintegration/priceminister/downloadallproducts',
  lazada_existingData: '/channelintegration/lazada',
  lazada_testConnection: '/channelintegration/lazada/testconnection',
  lazada_downloadRecent_prod: '/channelintegration/lazada/downloadrecentproducts',
  lazada_download_all_prod: '/channelintegration/lazada/downloadallproducts',
  lazada_tocken: '/channelintegration/generatelazadatoken',
  bonanza_existingData: '/channelintegration/bonanza',
  bonanza_testConnection: '/channelintegration/bonanza/testconnection',
  bonanza_downloadRecent_prod: '/channelintegration/bonanza/downloadrecentproducts',
  bonanza_download_all_prod: '/channelintegration/bonanza/downloadallproducts',
  bonanza_tocken: '/generatebonanzatoken',
  shopee_existingData: '/channelintegration/shopee',
  shopee_testConnection: '/channelintegration/shopee/testconnection',
  shopee_downloadRecent_prod: '/channelintegration/shopee/downloadrecentproducts',
  shopee_download_all_prod: '/channelintegration/shopee/downloadallproducts',
  opencart_existingData: '/channelintegration/opencart',
  opencart_testConnection: '/channelintegration/opencart/testconnection',
  opencart_downloadRecent_prod: '/channelintegration/opencart/downloadrecentproducts',
  opencart_download_all_prod: '/channelintegration/opencart/downloadallproducts',
  magento_existingData: '/channelintegration/magento',
  magento_testConnection: '/channelintegration/magento/testconnection',
  magento_downloadRecent_prod: '/channelintegration/magento/downloadrecentproducts',
  magento_download_all_prod: '/channelintegration/magento/downloadallproducts',
  volusion_existingData: '/channelintegration/volusion',
  volusion_testConnection: '/channelintegration/volusion/testconnection',
  volusion_downloadRecent_prod: '/channelintegration/volusion/downloadrecentproducts',
  volusion_download_all_prod: '/channelintegration/volusion/downloadallproducts',
  bluepark_existingData: '/channelintegration/bluepark',
  bluepark_testConnection: '/channelintegration/bluepark/testconnection',
  bluepark_downloadRecent_prod: '/channelintegration/bluepark/downloadrecentproducts',
  bluepark_download_all_prod: '/channelintegration/bluepark/downloadallproducts',
  xcart_existingData: '/channelintegration/xcart',
  xcart_testConnection: '/channelintegration/xcart/testconnection',
  xcart_downloadRecent_prod: '/channelintegration/xcart/downloadrecentproducts',
  xcart_download_all_prod: '/channelintegration/xcart/downloadallproducts',
  connect_to_xero:'/xerorequest2',
  enable_accounting:'/enableaccounting',
  index:'/index',
  xero_testconnection:'/testconnection',
  edit_accounting:'/editaccount',
  enablechannelforaccounting:'/enablechannelforaccounting',
  uploadtoxero:'/uploadtoxero',
  savexero:'/savexero',
  download_orders_from_xero:'/downloadvaluesfromxero',

  //User Management
  user_manageUser: '/user',
  //Registration
  reg_registration: '/registernew',
  //Settings
  get_printers: '/rest/getPrinters',
  set_generalsettings: '/generalsetting',
  set_unusedbarcode: '/findunusedbarcodes',
  set_usedbarcode: '/findbarcodes',
  set_skubarcode: '/findconvertskutobarcodes',
  set_bulkaction: '/exportfile',
  set_removebulkimport: '/removeimportfile',
  set_savedefault: '/savedefaultsettings',
  set_emailSetting: '/emailsetting',
  set_testmailcon: '/testsmtpconnection',
  set_savemailcon: '/saveemtpdetails',
  set_notification: '/loadnotifcations',
  set_syncchannel: '/synchronizesettings',
  set_shippingrulrs: '/shippingrules',
  set_saveattribute: '/saveattribute',
  set_saveattributeset: '/saveattributeset',
  set_saveattributesetValue: '/saveattributevaluestoset',
  set_editattribute: '/editattribute',
  set_editattributeset: '/editattributeset',
  set_removeattribute: '/removeattribute',
  set_removeattributeset: '/removeattributeset',
  set_removeexport: '/removeexportfile',
  set_removeimport: '/removeimportfile',
  set_removeshippingrule: '/removeshippingrules',
  set_removesmtp: '/removesmtpconnection',
  set_synchronizesku: '/removesynchronizesku',
  set_bulkimportfile: '/bulkimportfile',
  set_edittaxrate: '/edittaxrate',
  set_savetaxrate: '/updatetaxrate',
  set_savecurrency: '/savegeneraldetailcurrency',
  set_customizepacklist: '/customizepacklist',
  set_customizepicklist: '/customizepicklist',
  set_removetaxrate: '/removetaxrate',
  set_addunusedbarcode: '/updateautoadd',
  set_updatepicklist: '/updatecustompicklist',
  set_updatepacklist: '/updatecustompacklist',
  set_savesyncsettings: '/savesynchronizesettings',
  set_savelowstock: '/savelowstockalertemail',
  set_saveneworderemail: '/saveneworderemailseller',
  set_savenewordersms: '/savenewordersmsseller',
  set_saveshippingrules: '/saveshippingrules',
  set_editshippingrules: '/editshippingrules',
  delete_integration: '/channelintegration',
  user_subscription: '/subscriptions',
  user_priceplans: '/priceplans',
  user_add: '/savegeneraldetails',
  label_setup: '/shippingcourier/labelsetup',
  user_edit: '/edituser',
  user_update: '/updateuser',
  user_remove: '/removeuser',
  user_accountSettings: '/myaccountsettings',
  invoice_printed: '/new/invoiceprinted',
  label_printed: '/new/labelprinted',
  generate_printLabel: '/new/generateintegratedlabels',
  get_printLabel: '/new/labelprinted',
  create_product: '/rest/createproduct',
  edit_product: '/rest/editproduct',
  edit_channel_product: '/rest/editchannelproduct',
  save_general: '/rest/khubproductsavegeneral',
  save_ku_details: '/rest/khubproductsaveskudetails',
  save_variations: '/rest/saveproductvariationlist',

  upload_image: '/rest/productUploadImages',
  saveAttributes: '/rest/saveProductAttributes',
  find_images_based_on_product: '/rest/findProductImages',
  user_editaccountsubuserpermissions: '/editaccountsubuserpermissions',
  user_savepermissions: '/savepermissions',
  remove_image: '/rest/removeproductimages',
  get_purchase_orders: "/rest/getpurchaseorderslist",
  removesynchronizesku: '/removesynchronizesku',
  invoice_templates: '/invoicetemplates',
  edit_invoice: "/editinvoicetemplate",
  updateordershipping: '/new/updateordershipping',
  updatePaymentMethodForOrder: '/new/updatePaymentMethodForOrder',
  update_qty: '/rest/updateqtyforsku',
  update_qty1: '/rest/updateqtyforsku1',
  updateChannelProductQtyForSku: '/rest/updateChannelProductQtyForSku',
  createTicket: '/createticket',
  callback: '/callback',
  merge_product_list: '/rest/mergeproducts',
  start_merge_prod: '/rest/startmergeproduct',
  duplicate_product: '/rest/duplicateproduct',
  delete_product: '/rest/removeproduct',
  print_product: '/rest/printproduct',
  findDetials_in_channel_products: '/rest/findqtyforsku',
  find_warehouselocationsforproducts: '/warehouse/findwarehouselocationsforproducts',
  saveImages_inproduct: '/rest/saveproductimages',
  imagesForMapping: '/rest/findproductimagemappings',
  save_child_images: '/rest/savechildimages',

  // ebay
  listingtemplate: '/channellistingtemplate',

  // etsy

  getetsytemplate: '',
  delete_po: '/rest/deletepurchaseorderheader',
  display_supplier_products: '/rest/displaySupplierProducts',
  edit_po: '/rest/editpurchaseorder',
  save_po: '/rest/savepurchaseorder',
  save_po_header: '/rest/savepurchaseorderheader',
  print_po: '/rest/printpurchaseorder',
  email_po: '/new/emailpurchaseorder',
  save_template: '/saveinvoicetemplate',
  verify_bundle: '/rest/validateProductsNotBundled',
  list_now: '/rest/updatetochannel',
  updatetochannel: '/channel/updatetochannel',
  removechannelproductOnly: '/rest/removechannelproductOnly',
  schedule_listing: '/rest/schedulelistng',
  // invoice_print_path:"http://localhost:4200/sellershub/printinvoice",
  // label_print_path:"http://localhost:4200/sellershub/printlabels",
  create_po: '/rest/createpurchaseorder',
  bundle_prods_modal: '/rest/startsearchaddtobundle',

  find_bundle_prods: '/rest/findbundleproduts',
  update_save_bundle_chaild_items: '/rest/updatesavebundlechilditems',
  add_bundle: '/rest/addtobundle',
  remove_bundle_prod: '/rest/removekartzhubproductfromgroup',

  findebaycategories: '/findebaycategories',
  loadebaycategories: '/loadebaycategories',
  loadebaystorecategories: '/loadebaystorecategories',
  downloadebaylatestpolices: '/downloadebaylatestpolices',
  loadetsycategories: '/loadetsycategories',
  loadshopifystorecategories: '/loadshopifystorecategories',
  enable_equal_qty: '/rest/enableEditQty',
  deleteSubscrption: '/deleteAccountRequest',
  saveshippinglabel: '/saveshippinglabel',
  savechannelproduct: '/rest/savechannelproduct',
  removewaitinglist: '/rest/removewaitinglist',
  cancel_label: '/new/cancelamazonshipping',
  after_cancel_label: '/new/labelNotprinted',
  editshippinglabel: '/editshippinglabel',
  //Channel product update
  resetPassword: '/submitforgotuserdetailsapi',
  uploadImagesFromurl: '/rest/uploadimagesfromurl',
  stockRepricerSettings: '/rest/stockrepricer/updatepricerules',
  find_product_attributes: '/findchannelattributes',

  stockRepricerRules: '/rest/stockrepricer/findamazonrepricerules',
  stockfindAllItems: '/rest/stockrepricer/findallitems',
  findStockRepriceItems: '/rest/stockrepricer/findstockrepriceritems',
  findNotReseterItems: '/rest/stockrepricer/findnotresetitems',
  savepurchaseorderlines: '/rest/savepurchaseorderlines',
  paymentmethods: '/paymentmethods',
  submitPayment: '/submitpayment',

  emailconfig: '/emailconfig',
  saveemtpconfig: '/saveemtpconfig',
  testsmtpconfig: '/testsmtpconfig',
  removesmtpconfig: '/removesmtpconfig',
  activatesmtpconfig: '/activatesmtpconfig',
  po_email: '/new/sendpurchaseorderemail',

  savetemplateproductattributes: '/savetemplateproductattributes',
  productcategory: "/productcategory",
  create_productcategory: "/productcategory",
  delete_productcategory: "/productcategory/delete",
  findskulike: '/findskulike',
  inverntory_trcking: "/inventorytrack/transaction",

  findSupplierForProduct: "/new/suppliers/info",
  passwordResetSubmit: '/passwordreset/submit',
  deletepurchaseorderline: '/rest/deletepurchaseorderline',
  pdftoblob: '/new/blobs',
  s3Image: '/new/s3Image',
  pdftoblobDuplex: '/new/duplexPrint',
  composition: '/rest/composition',
  barcode: '/rest/barcode2',
  etsycallback: '/etsycallback',
  amzbuyshippingmethods: '/new/amzbuyshippingmethods',
  shippingcourier_template: '/shippingcourier/template',
  shipping_manifests:'/new/carrierCount',
  view_shipping_manifests:'/new/filterSearch',
  generate_manifest:'/new/manifestIdGeneration',
  retrieve_manifestId:'/new/retrieveManifestId',
  export_manifest:'/new/exportManifestDetails',
  retrieve_allmanifestIds:'/new/retrieveAllManifestIds',

  /* FBA */
  fba_plans:'/fba/plans',
  fba_prepInstructions:'/fba/prepInstructions',
  fba_create_inbound:'/fba/createInbound',
  fba_update_inbound:'/fba/updateInbound',
  /* Virtual printer */
  getPrinters:'/rest/getPrinters',
  deletePrinter:'/rest/deletePrinter',
  getPrintjob:'/rest/getPrintjob',
  getPrintjobs:'/rest/getPrintjobs',
  updatePrintjob:'/rest/updatePrintjob',
  createPrintjob:'/rest/createPrintjob',
};

/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
